%文件顺序应当与目录一致
%否则图 表 源码 ……
%索引会出现顺序错误

main_index.txt
foreword/foreword.txt
chapter01/chapter01.txt
chapter01/section01_chapter01.txt
chapter01/setup_dev_env_on_windows.txt
chapter01/setup_dev_env_on_linux.txt
chapter01/introduce_qmake.txt
chapter01/first_application.txt
chapter01/hellow_world.txt
chapter01/defaultstyle.txt
chapter01/use_shader_in_qt_quick.txt
chapter01/directdrawbyopengl.txt
chapter02/chapter02.txt
chapter03/chapter03.txt
chapter04/chapter04.txt
chapter05/chapter05.txt
chapter06/chapter06.txt
chapter07/chapter07.txt
chapter08/chapter08.txt
chapter09/chapter09.txt
chapter10/chapter10.txt



 

















