#pragma once

#include "sstd_glew.hpp"

#ifndef USING_SSTD_GLEW
#define USING_SSTD_GLEW \
using sstd::glActiveShaderProgram ; \
using sstd::glActiveTexture ; \
using sstd::glAttachShader ; \
using sstd::glBeginConditionalRender ; \
using sstd::glBeginQuery ; \
using sstd::glBeginQueryIndexed ; \
using sstd::glBeginTransformFeedback ; \
using sstd::glBindAttribLocation ; \
using sstd::glBindBuffer ; \
using sstd::glBindBufferBase ; \
using sstd::glBindBufferRange ; \
using sstd::glBindBuffersBase ; \
using sstd::glBindBuffersRange ; \
using sstd::glBindFragDataLocation ; \
using sstd::glBindFragDataLocationIndexed ; \
using sstd::glBindFramebuffer ; \
using sstd::glBindImageTexture ; \
using sstd::glBindImageTextures ; \
using sstd::glBindProgramPipeline ; \
using sstd::glBindRenderbuffer ; \
using sstd::glBindSampler ; \
using sstd::glBindSamplers ; \
using sstd::glBindTexture ; \
using sstd::glBindTextureUnit ; \
using sstd::glBindTextures ; \
using sstd::glBindTransformFeedback ; \
using sstd::glBindVertexArray ; \
using sstd::glBindVertexBuffer ; \
using sstd::glBindVertexBuffers ; \
using sstd::glBlendColor ; \
using sstd::glBlendEquation ; \
using sstd::glBlendEquationSeparate ; \
using sstd::glBlendEquationSeparatei ; \
using sstd::glBlendEquationi ; \
using sstd::glBlendFunc ; \
using sstd::glBlendFuncSeparate ; \
using sstd::glBlendFuncSeparatei ; \
using sstd::glBlendFunci ; \
using sstd::glBlitFramebuffer ; \
using sstd::glBlitNamedFramebuffer ; \
using sstd::glBufferData ; \
using sstd::glBufferStorage ; \
using sstd::glBufferSubData ; \
using sstd::glCheckFramebufferStatus ; \
using sstd::glCheckNamedFramebufferStatus ; \
using sstd::glClampColor ; \
using sstd::glClear ; \
using sstd::glClearBufferData ; \
using sstd::glClearBufferSubData ; \
using sstd::glClearBufferfi ; \
using sstd::glClearBufferfv ; \
using sstd::glClearBufferiv ; \
using sstd::glClearBufferuiv ; \
using sstd::glClearColor ; \
using sstd::glClearDepth ; \
using sstd::glClearDepthf ; \
using sstd::glClearNamedBufferData ; \
using sstd::glClearNamedBufferSubData ; \
using sstd::glClearNamedFramebufferfi ; \
using sstd::glClearNamedFramebufferfv ; \
using sstd::glClearNamedFramebufferiv ; \
using sstd::glClearNamedFramebufferuiv ; \
using sstd::glClearStencil ; \
using sstd::glClearTexImage ; \
using sstd::glClearTexSubImage ; \
using sstd::glClientWaitSync ; \
using sstd::glClipControl ; \
using sstd::glColorMask ; \
using sstd::glColorMaski ; \
using sstd::glCompileShader ; \
using sstd::glCompressedTexImage1D ; \
using sstd::glCompressedTexImage2D ; \
using sstd::glCompressedTexImage3D ; \
using sstd::glCompressedTexSubImage1D ; \
using sstd::glCompressedTexSubImage2D ; \
using sstd::glCompressedTexSubImage3D ; \
using sstd::glCompressedTextureSubImage1D ; \
using sstd::glCompressedTextureSubImage2D ; \
using sstd::glCompressedTextureSubImage3D ; \
using sstd::glCopyBufferSubData ; \
using sstd::glCopyImageSubData ; \
using sstd::glCopyNamedBufferSubData ; \
using sstd::glCopyTexImage1D ; \
using sstd::glCopyTexImage2D ; \
using sstd::glCopyTexSubImage1D ; \
using sstd::glCopyTexSubImage2D ; \
using sstd::glCopyTexSubImage3D ; \
using sstd::glCopyTextureSubImage1D ; \
using sstd::glCopyTextureSubImage2D ; \
using sstd::glCopyTextureSubImage3D ; \
using sstd::glCreateBuffers ; \
using sstd::glCreateFramebuffers ; \
using sstd::glCreateProgram ; \
using sstd::glCreateProgramPipelines ; \
using sstd::glCreateQueries ; \
using sstd::glCreateRenderbuffers ; \
using sstd::glCreateSamplers ; \
using sstd::glCreateShader ; \
using sstd::glCreateShaderProgramv ; \
using sstd::glCreateTextures ; \
using sstd::glCreateTransformFeedbacks ; \
using sstd::glCreateVertexArrays ; \
using sstd::glCullFace ; \
using sstd::glDebugMessageCallback ; \
using sstd::glDebugMessageControl ; \
using sstd::glDebugMessageInsert ; \
using sstd::glDeleteBuffers ; \
using sstd::glDeleteFramebuffers ; \
using sstd::glDeleteProgram ; \
using sstd::glDeleteProgramPipelines ; \
using sstd::glDeleteQueries ; \
using sstd::glDeleteRenderbuffers ; \
using sstd::glDeleteSamplers ; \
using sstd::glDeleteShader ; \
using sstd::glDeleteSync ; \
using sstd::glDeleteTextures ; \
using sstd::glDeleteTransformFeedbacks ; \
using sstd::glDeleteVertexArrays ; \
using sstd::glDepthFunc ; \
using sstd::glDepthMask ; \
using sstd::glDepthRange ; \
using sstd::glDepthRangeArrayv ; \
using sstd::glDepthRangeIndexed ; \
using sstd::glDepthRangef ; \
using sstd::glDetachShader ; \
using sstd::glDisable ; \
using sstd::glDisableVertexArrayAttrib ; \
using sstd::glDisableVertexAttribArray ; \
using sstd::glDisablei ; \
using sstd::glDispatchCompute ; \
using sstd::glDispatchComputeIndirect ; \
using sstd::glDrawArrays ; \
using sstd::glDrawArraysIndirect ; \
using sstd::glDrawArraysInstanced ; \
using sstd::glDrawArraysInstancedBaseInstance ; \
using sstd::glDrawBuffer ; \
using sstd::glDrawBuffers ; \
using sstd::glDrawElements ; \
using sstd::glDrawElementsBaseVertex ; \
using sstd::glDrawElementsIndirect ; \
using sstd::glDrawElementsInstanced ; \
using sstd::glDrawElementsInstancedBaseInstance ; \
using sstd::glDrawElementsInstancedBaseVertex ; \
using sstd::glDrawElementsInstancedBaseVertexBaseInstance ; \
using sstd::glDrawRangeElements ; \
using sstd::glDrawRangeElementsBaseVertex ; \
using sstd::glDrawTransformFeedback ; \
using sstd::glDrawTransformFeedbackInstanced ; \
using sstd::glDrawTransformFeedbackStream ; \
using sstd::glDrawTransformFeedbackStreamInstanced ; \
using sstd::glEnable ; \
using sstd::glEnableVertexArrayAttrib ; \
using sstd::glEnableVertexAttribArray ; \
using sstd::glEnablei ; \
using sstd::glEndConditionalRender ; \
using sstd::glEndQuery ; \
using sstd::glEndQueryIndexed ; \
using sstd::glEndTransformFeedback ; \
using sstd::glFenceSync ; \
using sstd::glFinish ; \
using sstd::glFlush ; \
using sstd::glFlushMappedBufferRange ; \
using sstd::glFlushMappedNamedBufferRange ; \
using sstd::glFramebufferParameteri ; \
using sstd::glFramebufferRenderbuffer ; \
using sstd::glFramebufferTexture ; \
using sstd::glFramebufferTexture1D ; \
using sstd::glFramebufferTexture2D ; \
using sstd::glFramebufferTexture3D ; \
using sstd::glFramebufferTextureLayer ; \
using sstd::glFrontFace ; \
using sstd::glGenBuffers ; \
using sstd::glGenFramebuffers ; \
using sstd::glGenProgramPipelines ; \
using sstd::glGenQueries ; \
using sstd::glGenRenderbuffers ; \
using sstd::glGenSamplers ; \
using sstd::glGenTextures ; \
using sstd::glGenTransformFeedbacks ; \
using sstd::glGenVertexArrays ; \
using sstd::glGenerateMipmap ; \
using sstd::glGenerateTextureMipmap ; \
using sstd::glGetActiveAtomicCounterBufferiv ; \
using sstd::glGetActiveAttrib ; \
using sstd::glGetActiveSubroutineName ; \
using sstd::glGetActiveSubroutineUniformName ; \
using sstd::glGetActiveSubroutineUniformiv ; \
using sstd::glGetActiveUniform ; \
using sstd::glGetActiveUniformBlockName ; \
using sstd::glGetActiveUniformBlockiv ; \
using sstd::glGetActiveUniformName ; \
using sstd::glGetActiveUniformsiv ; \
using sstd::glGetAttachedShaders ; \
using sstd::glGetAttribLocation ; \
using sstd::glGetBooleani_v ; \
using sstd::glGetBooleanv ; \
using sstd::glGetBufferParameteri64v ; \
using sstd::glGetBufferParameteriv ; \
using sstd::glGetBufferPointerv ; \
using sstd::glGetBufferSubData ; \
using sstd::glGetCompressedTexImage ; \
using sstd::glGetCompressedTextureImage ; \
using sstd::glGetCompressedTextureSubImage ; \
using sstd::glGetDebugMessageLog ; \
using sstd::glGetDoublei_v ; \
using sstd::glGetDoublev ; \
using sstd::glGetError ; \
using sstd::glGetFloati_v ; \
using sstd::glGetFloatv ; \
using sstd::glGetFragDataIndex ; \
using sstd::glGetFragDataLocation ; \
using sstd::glGetFramebufferAttachmentParameteriv ; \
using sstd::glGetFramebufferParameteriv ; \
using sstd::glGetGraphicsResetStatus ; \
using sstd::glGetInteger64i_v ; \
using sstd::glGetInteger64v ; \
using sstd::glGetIntegeri_v ; \
using sstd::glGetIntegerv ; \
using sstd::glGetInternalformati64v ; \
using sstd::glGetInternalformativ ; \
using sstd::glGetMultisamplefv ; \
using sstd::glGetNamedBufferParameteri64v ; \
using sstd::glGetNamedBufferParameteriv ; \
using sstd::glGetNamedBufferPointerv ; \
using sstd::glGetNamedBufferSubData ; \
using sstd::glGetNamedFramebufferAttachmentParameteriv ; \
using sstd::glGetNamedFramebufferParameteriv ; \
using sstd::glGetNamedRenderbufferParameteriv ; \
using sstd::glGetObjectLabel ; \
using sstd::glGetObjectPtrLabel ; \
using sstd::glGetProgramBinary ; \
using sstd::glGetProgramInfoLog ; \
using sstd::glGetProgramInterfaceiv ; \
using sstd::glGetProgramPipelineInfoLog ; \
using sstd::glGetProgramPipelineiv ; \
using sstd::glGetProgramResourceIndex ; \
using sstd::glGetProgramResourceLocation ; \
using sstd::glGetProgramResourceLocationIndex ; \
using sstd::glGetProgramResourceName ; \
using sstd::glGetProgramResourceiv ; \
using sstd::glGetProgramStageiv ; \
using sstd::glGetProgramiv ; \
using sstd::glGetQueryIndexediv ; \
using sstd::glGetQueryObjecti64v ; \
using sstd::glGetQueryObjectiv ; \
using sstd::glGetQueryObjectui64v ; \
using sstd::glGetQueryObjectuiv ; \
using sstd::glGetQueryiv ; \
using sstd::glGetRenderbufferParameteriv ; \
using sstd::glGetSamplerParameterIiv ; \
using sstd::glGetSamplerParameterIuiv ; \
using sstd::glGetSamplerParameterfv ; \
using sstd::glGetSamplerParameteriv ; \
using sstd::glGetShaderInfoLog ; \
using sstd::glGetShaderPrecisionFormat ; \
using sstd::glGetShaderSource ; \
using sstd::glGetShaderiv ; \
using sstd::glGetString ; \
using sstd::glGetStringi ; \
using sstd::glGetSubroutineIndex ; \
using sstd::glGetSubroutineUniformLocation ; \
using sstd::glGetSynciv ; \
using sstd::glGetTexImage ; \
using sstd::glGetTexLevelParameterfv ; \
using sstd::glGetTexLevelParameteriv ; \
using sstd::glGetTexParameterIiv ; \
using sstd::glGetTexParameterIuiv ; \
using sstd::glGetTexParameterfv ; \
using sstd::glGetTexParameteriv ; \
using sstd::glGetTextureImage ; \
using sstd::glGetTextureLevelParameterfv ; \
using sstd::glGetTextureLevelParameteriv ; \
using sstd::glGetTextureParameterIiv ; \
using sstd::glGetTextureParameterIuiv ; \
using sstd::glGetTextureParameterfv ; \
using sstd::glGetTextureParameteriv ; \
using sstd::glGetTextureSubImage ; \
using sstd::glGetTransformFeedbackVarying ; \
using sstd::glGetTransformFeedbacki64_v ; \
using sstd::glGetTransformFeedbacki_v ; \
using sstd::glGetTransformFeedbackiv ; \
using sstd::glGetUniformBlockIndex ; \
using sstd::glGetUniformIndices ; \
using sstd::glGetUniformLocation ; \
using sstd::glGetUniformSubroutineuiv ; \
using sstd::glGetUniformdv ; \
using sstd::glGetUniformfv ; \
using sstd::glGetUniformiv ; \
using sstd::glGetUniformuiv ; \
using sstd::glGetVertexArrayIndexed64iv ; \
using sstd::glGetVertexArrayIndexediv ; \
using sstd::glGetVertexArrayiv ; \
using sstd::glGetVertexAttribIiv ; \
using sstd::glGetVertexAttribIuiv ; \
using sstd::glGetVertexAttribLdv ; \
using sstd::glGetVertexAttribPointerv ; \
using sstd::glGetVertexAttribdv ; \
using sstd::glGetVertexAttribfv ; \
using sstd::glGetVertexAttribiv ; \
using sstd::glGetnCompressedTexImage ; \
using sstd::glGetnTexImage ; \
using sstd::glGetnUniformdv ; \
using sstd::glGetnUniformfv ; \
using sstd::glGetnUniformiv ; \
using sstd::glGetnUniformuiv ; \
using sstd::glHint ; \
using sstd::glInvalidateBufferData ; \
using sstd::glInvalidateBufferSubData ; \
using sstd::glInvalidateFramebuffer ; \
using sstd::glInvalidateNamedFramebufferData ; \
using sstd::glInvalidateNamedFramebufferSubData ; \
using sstd::glInvalidateSubFramebuffer ; \
using sstd::glInvalidateTexImage ; \
using sstd::glInvalidateTexSubImage ; \
using sstd::glIsBuffer ; \
using sstd::glIsEnabled ; \
using sstd::glIsEnabledi ; \
using sstd::glIsFramebuffer ; \
using sstd::glIsProgram ; \
using sstd::glIsProgramPipeline ; \
using sstd::glIsQuery ; \
using sstd::glIsRenderbuffer ; \
using sstd::glIsSampler ; \
using sstd::glIsShader ; \
using sstd::glIsSync ; \
using sstd::glIsTexture ; \
using sstd::glIsTransformFeedback ; \
using sstd::glIsVertexArray ; \
using sstd::glLineWidth ; \
using sstd::glLinkProgram ; \
using sstd::glLogicOp ; \
using sstd::glMapBuffer ; \
using sstd::glMapBufferRange ; \
using sstd::glMapNamedBuffer ; \
using sstd::glMapNamedBufferRange ; \
using sstd::glMemoryBarrier ; \
using sstd::glMemoryBarrierByRegion ; \
using sstd::glMinSampleShading ; \
using sstd::glMultiDrawArrays ; \
using sstd::glMultiDrawArraysIndirect ; \
using sstd::glMultiDrawElements ; \
using sstd::glMultiDrawElementsBaseVertex ; \
using sstd::glMultiDrawElementsIndirect ; \
using sstd::glNamedBufferData ; \
using sstd::glNamedBufferStorage ; \
using sstd::glNamedBufferSubData ; \
using sstd::glNamedFramebufferDrawBuffer ; \
using sstd::glNamedFramebufferDrawBuffers ; \
using sstd::glNamedFramebufferParameteri ; \
using sstd::glNamedFramebufferReadBuffer ; \
using sstd::glNamedFramebufferRenderbuffer ; \
using sstd::glNamedFramebufferTexture ; \
using sstd::glNamedFramebufferTextureLayer ; \
using sstd::glNamedRenderbufferStorage ; \
using sstd::glNamedRenderbufferStorageMultisample ; \
using sstd::glObjectLabel ; \
using sstd::glObjectPtrLabel ; \
using sstd::glPatchParameterfv ; \
using sstd::glPatchParameteri ; \
using sstd::glPauseTransformFeedback ; \
using sstd::glPixelStoref ; \
using sstd::glPixelStorei ; \
using sstd::glPointParameterf ; \
using sstd::glPointParameterfv ; \
using sstd::glPointParameteri ; \
using sstd::glPointParameteriv ; \
using sstd::glPointSize ; \
using sstd::glPolygonMode ; \
using sstd::glPolygonOffset ; \
using sstd::glPopDebugGroup ; \
using sstd::glPrimitiveRestartIndex ; \
using sstd::glProgramBinary ; \
using sstd::glProgramParameteri ; \
using sstd::glProgramUniform1d ; \
using sstd::glProgramUniform1dv ; \
using sstd::glProgramUniform1f ; \
using sstd::glProgramUniform1fv ; \
using sstd::glProgramUniform1i ; \
using sstd::glProgramUniform1iv ; \
using sstd::glProgramUniform1ui ; \
using sstd::glProgramUniform1uiv ; \
using sstd::glProgramUniform2d ; \
using sstd::glProgramUniform2dv ; \
using sstd::glProgramUniform2f ; \
using sstd::glProgramUniform2fv ; \
using sstd::glProgramUniform2i ; \
using sstd::glProgramUniform2iv ; \
using sstd::glProgramUniform2ui ; \
using sstd::glProgramUniform2uiv ; \
using sstd::glProgramUniform3d ; \
using sstd::glProgramUniform3dv ; \
using sstd::glProgramUniform3f ; \
using sstd::glProgramUniform3fv ; \
using sstd::glProgramUniform3i ; \
using sstd::glProgramUniform3iv ; \
using sstd::glProgramUniform3ui ; \
using sstd::glProgramUniform3uiv ; \
using sstd::glProgramUniform4d ; \
using sstd::glProgramUniform4dv ; \
using sstd::glProgramUniform4f ; \
using sstd::glProgramUniform4fv ; \
using sstd::glProgramUniform4i ; \
using sstd::glProgramUniform4iv ; \
using sstd::glProgramUniform4ui ; \
using sstd::glProgramUniform4uiv ; \
using sstd::glProgramUniformMatrix2dv ; \
using sstd::glProgramUniformMatrix2fv ; \
using sstd::glProgramUniformMatrix2x3dv ; \
using sstd::glProgramUniformMatrix2x3fv ; \
using sstd::glProgramUniformMatrix2x4dv ; \
using sstd::glProgramUniformMatrix2x4fv ; \
using sstd::glProgramUniformMatrix3dv ; \
using sstd::glProgramUniformMatrix3fv ; \
using sstd::glProgramUniformMatrix3x2dv ; \
using sstd::glProgramUniformMatrix3x2fv ; \
using sstd::glProgramUniformMatrix3x4dv ; \
using sstd::glProgramUniformMatrix3x4fv ; \
using sstd::glProgramUniformMatrix4dv ; \
using sstd::glProgramUniformMatrix4fv ; \
using sstd::glProgramUniformMatrix4x2dv ; \
using sstd::glProgramUniformMatrix4x2fv ; \
using sstd::glProgramUniformMatrix4x3dv ; \
using sstd::glProgramUniformMatrix4x3fv ; \
using sstd::glProvokingVertex ; \
using sstd::glPushDebugGroup ; \
using sstd::glQueryCounter ; \
using sstd::glReadBuffer ; \
using sstd::glReadPixels ; \
using sstd::glReadnPixels ; \
using sstd::glReleaseShaderCompiler ; \
using sstd::glRenderbufferStorage ; \
using sstd::glRenderbufferStorageMultisample ; \
using sstd::glResumeTransformFeedback ; \
using sstd::glSampleCoverage ; \
using sstd::glSampleMaski ; \
using sstd::glSamplerParameterIiv ; \
using sstd::glSamplerParameterIuiv ; \
using sstd::glSamplerParameterf ; \
using sstd::glSamplerParameterfv ; \
using sstd::glSamplerParameteri ; \
using sstd::glSamplerParameteriv ; \
using sstd::glScissor ; \
using sstd::glScissorArrayv ; \
using sstd::glScissorIndexed ; \
using sstd::glScissorIndexedv ; \
using sstd::glShaderBinary ; \
using sstd::glShaderSource ; \
using sstd::glShaderStorageBlockBinding ; \
using sstd::glStencilFunc ; \
using sstd::glStencilFuncSeparate ; \
using sstd::glStencilMask ; \
using sstd::glStencilMaskSeparate ; \
using sstd::glStencilOp ; \
using sstd::glStencilOpSeparate ; \
using sstd::glTexBuffer ; \
using sstd::glTexBufferRange ; \
using sstd::glTexImage1D ; \
using sstd::glTexImage2D ; \
using sstd::glTexImage2DMultisample ; \
using sstd::glTexImage3D ; \
using sstd::glTexImage3DMultisample ; \
using sstd::glTexParameterIiv ; \
using sstd::glTexParameterIuiv ; \
using sstd::glTexParameterf ; \
using sstd::glTexParameterfv ; \
using sstd::glTexParameteri ; \
using sstd::glTexParameteriv ; \
using sstd::glTexStorage1D ; \
using sstd::glTexStorage2D ; \
using sstd::glTexStorage2DMultisample ; \
using sstd::glTexStorage3D ; \
using sstd::glTexStorage3DMultisample ; \
using sstd::glTexSubImage1D ; \
using sstd::glTexSubImage2D ; \
using sstd::glTexSubImage3D ; \
using sstd::glTextureBarrier ; \
using sstd::glTextureBuffer ; \
using sstd::glTextureBufferRange ; \
using sstd::glTextureParameterIiv ; \
using sstd::glTextureParameterIuiv ; \
using sstd::glTextureParameterf ; \
using sstd::glTextureParameterfv ; \
using sstd::glTextureParameteri ; \
using sstd::glTextureParameteriv ; \
using sstd::glTextureStorage1D ; \
using sstd::glTextureStorage2D ; \
using sstd::glTextureStorage2DMultisample ; \
using sstd::glTextureStorage3D ; \
using sstd::glTextureStorage3DMultisample ; \
using sstd::glTextureSubImage1D ; \
using sstd::glTextureSubImage2D ; \
using sstd::glTextureSubImage3D ; \
using sstd::glTextureView ; \
using sstd::glTransformFeedbackBufferBase ; \
using sstd::glTransformFeedbackBufferRange ; \
using sstd::glTransformFeedbackVaryings ; \
using sstd::glUniform1d ; \
using sstd::glUniform1dv ; \
using sstd::glUniform1f ; \
using sstd::glUniform1fv ; \
using sstd::glUniform1i ; \
using sstd::glUniform1iv ; \
using sstd::glUniform1ui ; \
using sstd::glUniform1uiv ; \
using sstd::glUniform2d ; \
using sstd::glUniform2dv ; \
using sstd::glUniform2f ; \
using sstd::glUniform2fv ; \
using sstd::glUniform2i ; \
using sstd::glUniform2iv ; \
using sstd::glUniform2ui ; \
using sstd::glUniform2uiv ; \
using sstd::glUniform3d ; \
using sstd::glUniform3dv ; \
using sstd::glUniform3f ; \
using sstd::glUniform3fv ; \
using sstd::glUniform3i ; \
using sstd::glUniform3iv ; \
using sstd::glUniform3ui ; \
using sstd::glUniform3uiv ; \
using sstd::glUniform4d ; \
using sstd::glUniform4dv ; \
using sstd::glUniform4f ; \
using sstd::glUniform4fv ; \
using sstd::glUniform4i ; \
using sstd::glUniform4iv ; \
using sstd::glUniform4ui ; \
using sstd::glUniform4uiv ; \
using sstd::glUniformBlockBinding ; \
using sstd::glUniformMatrix2dv ; \
using sstd::glUniformMatrix2fv ; \
using sstd::glUniformMatrix2x3dv ; \
using sstd::glUniformMatrix2x3fv ; \
using sstd::glUniformMatrix2x4dv ; \
using sstd::glUniformMatrix2x4fv ; \
using sstd::glUniformMatrix3dv ; \
using sstd::glUniformMatrix3fv ; \
using sstd::glUniformMatrix3x2dv ; \
using sstd::glUniformMatrix3x2fv ; \
using sstd::glUniformMatrix3x4dv ; \
using sstd::glUniformMatrix3x4fv ; \
using sstd::glUniformMatrix4dv ; \
using sstd::glUniformMatrix4fv ; \
using sstd::glUniformMatrix4x2dv ; \
using sstd::glUniformMatrix4x2fv ; \
using sstd::glUniformMatrix4x3dv ; \
using sstd::glUniformMatrix4x3fv ; \
using sstd::glUniformSubroutinesuiv ; \
using sstd::glUnmapBuffer ; \
using sstd::glUnmapNamedBuffer ; \
using sstd::glUseProgram ; \
using sstd::glUseProgramStages ; \
using sstd::glValidateProgram ; \
using sstd::glValidateProgramPipeline ; \
using sstd::glVertexArrayAttribBinding ; \
using sstd::glVertexArrayAttribFormat ; \
using sstd::glVertexArrayAttribIFormat ; \
using sstd::glVertexArrayAttribLFormat ; \
using sstd::glVertexArrayBindingDivisor ; \
using sstd::glVertexArrayElementBuffer ; \
using sstd::glVertexArrayVertexBuffer ; \
using sstd::glVertexArrayVertexBuffers ; \
using sstd::glVertexAttrib1d ; \
using sstd::glVertexAttrib1dv ; \
using sstd::glVertexAttrib1f ; \
using sstd::glVertexAttrib1fv ; \
using sstd::glVertexAttrib1s ; \
using sstd::glVertexAttrib1sv ; \
using sstd::glVertexAttrib2d ; \
using sstd::glVertexAttrib2dv ; \
using sstd::glVertexAttrib2f ; \
using sstd::glVertexAttrib2fv ; \
using sstd::glVertexAttrib2s ; \
using sstd::glVertexAttrib2sv ; \
using sstd::glVertexAttrib3d ; \
using sstd::glVertexAttrib3dv ; \
using sstd::glVertexAttrib3f ; \
using sstd::glVertexAttrib3fv ; \
using sstd::glVertexAttrib3s ; \
using sstd::glVertexAttrib3sv ; \
using sstd::glVertexAttrib4Nbv ; \
using sstd::glVertexAttrib4Niv ; \
using sstd::glVertexAttrib4Nsv ; \
using sstd::glVertexAttrib4Nub ; \
using sstd::glVertexAttrib4Nubv ; \
using sstd::glVertexAttrib4Nuiv ; \
using sstd::glVertexAttrib4Nusv ; \
using sstd::glVertexAttrib4bv ; \
using sstd::glVertexAttrib4d ; \
using sstd::glVertexAttrib4dv ; \
using sstd::glVertexAttrib4f ; \
using sstd::glVertexAttrib4fv ; \
using sstd::glVertexAttrib4iv ; \
using sstd::glVertexAttrib4s ; \
using sstd::glVertexAttrib4sv ; \
using sstd::glVertexAttrib4ubv ; \
using sstd::glVertexAttrib4uiv ; \
using sstd::glVertexAttrib4usv ; \
using sstd::glVertexAttribBinding ; \
using sstd::glVertexAttribDivisor ; \
using sstd::glVertexAttribFormat ; \
using sstd::glVertexAttribI1i ; \
using sstd::glVertexAttribI1iv ; \
using sstd::glVertexAttribI1ui ; \
using sstd::glVertexAttribI1uiv ; \
using sstd::glVertexAttribI2i ; \
using sstd::glVertexAttribI2iv ; \
using sstd::glVertexAttribI2ui ; \
using sstd::glVertexAttribI2uiv ; \
using sstd::glVertexAttribI3i ; \
using sstd::glVertexAttribI3iv ; \
using sstd::glVertexAttribI3ui ; \
using sstd::glVertexAttribI3uiv ; \
using sstd::glVertexAttribI4bv ; \
using sstd::glVertexAttribI4i ; \
using sstd::glVertexAttribI4iv ; \
using sstd::glVertexAttribI4sv ; \
using sstd::glVertexAttribI4ubv ; \
using sstd::glVertexAttribI4ui ; \
using sstd::glVertexAttribI4uiv ; \
using sstd::glVertexAttribI4usv ; \
using sstd::glVertexAttribIFormat ; \
using sstd::glVertexAttribIPointer ; \
using sstd::glVertexAttribL1d ; \
using sstd::glVertexAttribL1dv ; \
using sstd::glVertexAttribL2d ; \
using sstd::glVertexAttribL2dv ; \
using sstd::glVertexAttribL3d ; \
using sstd::glVertexAttribL3dv ; \
using sstd::glVertexAttribL4d ; \
using sstd::glVertexAttribL4dv ; \
using sstd::glVertexAttribLFormat ; \
using sstd::glVertexAttribLPointer ; \
using sstd::glVertexAttribP1ui ; \
using sstd::glVertexAttribP1uiv ; \
using sstd::glVertexAttribP2ui ; \
using sstd::glVertexAttribP2uiv ; \
using sstd::glVertexAttribP3ui ; \
using sstd::glVertexAttribP3uiv ; \
using sstd::glVertexAttribP4ui ; \
using sstd::glVertexAttribP4uiv ; \
using sstd::glVertexAttribPointer ; \
using sstd::glVertexBindingDivisor ; \
using sstd::glViewport ; \
using sstd::glViewportArrayv ; \
using sstd::glViewportIndexedf ; \
using sstd::glViewportIndexedfv ; \
using sstd::glWaitSync ; \
static_assert(true,"true")
/**********************************************/
#endif
